/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function Advantages() {
  return (
    <div className="box-border flex relative flex-col shrink-0 pb-32 mt-8 mb-20 h-auto bg-neutral-100 max-[1040px]:mt-0 max-sm:mx-auto">
      <div className="box-border flex relative flex-col shrink-0 px-10 mt-7 max-[1040px]:mt-5 max-sm:mt-10">
        <div className="flex gap-5 max-[1040px]:flex-col">
          <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
            <div className="flex flex-col px-5 mt-7 w-full pb-10 bg-orange-50 max-[1040px]:pl-5">
              <div className="box-border flex relative flex-col shrink-0 mx-auto mt-5 w-[347px] max-sm:pl-20 max-sm:mx-auto max-sm:w-[364px]">
                <div className="flex gap-5">
                  <div className="flex flex-col w-12/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto h-auto text-base leading-6 text-amber-500">
                      ––
                    </div>
                  </div>
                  <div className="flex flex-col w-12/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-base leading-6 text-amber-500">
                      ADVANTAGES OF COCHE RIDE
                    </div>
                  </div>
                </div>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-4xl leading-10 text-black ">
                <p
                  // class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <br />
                </p>
                <h3
                  // class="display-4 mb-15 mb-md-6 px-lg-10"
                  className="px-10 mb-6 text-3xl span-bold tracking-normal leading-tight text-center text-slate-700"
                >
                  <span className="text-4xl font-extrabold mx-auto w-full">
                    {/* <span > */}
                      Benefits for our Customers, Brokers &amp; Transporters
                    {/* </span> */}
                  </span>
                </h3>
              </div>
              <div className="main_container box-border grid relative gap-5 mt-0.5 grid-cols-[repeat(3,1fr)] max-[1040px]:grid max-[1040px]:flex-col max-[1040px]:grid-cols-[repeat(2,1fr)] max-sm:grid max-sm:flex-row max-sm:pl-4 max-sm:mx-auto max-sm:grid-cols-[repeat(1,1fr)] max-sm:max-w-[auto]">
                <div className="column box-border flex relative flex-col shrink-0 pb-16 pl-5 mt-5 mr-5 bg-white rounded-3xl shadow-sm max-[1040px]:col-[span] max-sm:pl-5 max-sm:mr-auto max-sm:w-[300px]">
                  <div className="flex gap-5">
                    <div className="flex flex-col w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8ba0ac4cb7d244f2aaf69645b3267a72"
                        className="box-border object-cover overflow-hidden shrink-0 mt-5 mr-auto w-full aspect-square max-w-[46px] min-h-[20px] min-w-[20px]"
                      />
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <h4 className="mb-2 text-base span-bold tracking-normal leading-normal">
                          <span className="text-xl bg-white">
                            <span className="text-[#343f53]" >
                              Customers
                            </span>
                          </span>
                        </h4>
                      </div>
                      <div className="box-border flex relative flex-col shrink-0 mt-0 mr-auto">
                        <div className="flex gap-5 max-[1040px]:flex-col">
                          <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                            <div className="box-border flex relative flex-col shrink-0 mx-auto mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      // 
                                      classname="text-[#9399a4]"
                                    >
                                      Insured, efficient freight
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-[1040px]:w-[270px] max-sm:w-[239px]">
                                    <span
                                      // 
                                      className="text-[#9399a4]"
                                    >
                                      AI powered &amp; Efficient Route Planning
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-sm:w-[275px]">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Extensive Warehousing Network
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px] max-sm:w-[223px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-sm:ml-0">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Fair Pricing Model
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Real-time Visibility
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Data-driven Insights
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-sm:w-[271px]">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Enhanced Customer Experience
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="column box-border flex relative flex-col shrink-0 pl-5 mt-5 mr-5 bg-white rounded-3xl shadow-sm max-[1040px]:pb-16 max-[1040px]:col-[span_1] max-sm:pl-5 max-sm:mr-auto max-sm:w-[343px]">
                  <div className="flex gap-5">
                    <div className="flex flex-col w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F2b98f5cba2f6424a83c44dc58a6783c0"
                        className="box-border object-cover overflow-hidden shrink-0 mt-5 mr-auto w-full aspect-square max-w-[46px] min-h-[20px] min-w-[20px]"
                      />
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <h4 className="mb-2 text-base span-bold tracking-normal leading-normal">
                          <span className="text-xl bg-white">
                            <span className="text-[#343f53]" >
                              Brokers
                            </span>
                          </span>
                        </h4>
                      </div>
                      <div className="box-border flex relative flex-col shrink-0 mt-0 mr-auto">
                        <div className="flex gap-5 max-[1040px]:flex-col">
                          <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                            <div className="box-border flex relative flex-col shrink-0 mx-auto mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Insured, efficient freight
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-[1040px]:w-[258px] max-sm:w-[239px]">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      AI powered &amp; Efficient Route Planning
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 w-auto h-auto text-md leading-7 text-amber-500 max-sm:w-[271px]">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Extensive Warehousing Network
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Fair Pricing Model
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Real-time Visibility
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Data-driven Insights
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-sm:w-[278px]">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Enhanced Customer Experience
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="column box-border flex relative flex-col shrink-0 pl-5 mt-5 mr-2.5 bg-white rounded-3xl shadow-sm max-[1040px]:pb-10 max-[1040px]:mr-auto max-[1040px]:col-[span_3] max-sm:pl-5 max-sm:col-[span_1] max-sm:w-[300px]">
                  <div className="flex gap-5">
                    <div className="flex flex-col w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9d8af609e215470480b12df000e3ada4"
                        className="box-border object-cover overflow-hidden shrink-0 mt-5 mr-auto w-full aspect-square max-w-[46px] min-h-[20px] min-w-[20px]"
                      />
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <h4 className="mb-2 text-base span-bold tracking-normal leading-normal">
                          <span className="text-xl bg-white">
                            <span className="text-[#343f53]" >
                              Transporters
                            </span>
                          </span>
                        </h4>
                      </div>
                      <div className="box-border flex relative flex-col shrink-0 mt-0 mr-auto">
                        <div className="flex gap-5 max-[1040px]:flex-col">
                          <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                            <div className="box-border flex relative flex-col shrink-0 mx-auto mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Insured, efficient freight
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-[1040px]:w-[260px] max-sm:w-[238px]">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      AI powered &amp; Efficient Route Planning
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-sm:w-[272px]">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Extensive Warehousing Network
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Fair Pricing Model
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Real-time Visibility
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Data-driven Insights
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5 w-[280px]">
                              <div className="flex gap-5">
                                <div className="flex flex-col w-12/12">
                                  <img
                                    loading="lazy"
                                    src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff12c29dd99c843b4a19e54789835db45"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-6 mr-auto w-full aspect-square max-w-[23px] min-h-[20px] min-w-[20px]"
                                  />
                                </div>
                                <div className="flex flex-col w-12/12">
                                  <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-md leading-7 text-amber-500 max-sm:w-[275px]">
                                    <span
                                      
                                      className="text-[#9399a4]"
                                    >
                                      Enhanced Customer Experience
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
