/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function WhoWeAre() {
  return (
    <div className="box-border flex relative flex-col shrink-0 pt-8 mt-12 mb-5 bg-white h-[673px] max-[1040px]:px-5 max-[1040px]:mt-0 max-[1040px]:bg-white max-[1040px]:h-[1317px] max-sm:mt-1 max-sm:bg-white max-sm:h-[100%] max-sm:min-h-none max-sm:pb-[520px]">
      <div className="box-border flex relative flex-col shrink-0 justify-start px-10 pb-20 mt-0 mb-16 bg-white h-[1217.5px] max-sm:px-5 max-sm:mb-5 max-sm:bg-white max-sm:max-h-none max-sm:min-h-[817.5px]">
        <div className="flex gap-5 max-[1040px]:flex-col">
          <div className="flex flex-col w-6/12 max-[1040px]:ml-0 max-[1040px]:w-full">
            <div className="box-border flex relative flex-col shrink-0 px-5 mt-5">
              <div className="flex gap-5 max-[1040px]:flex-col">
                <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                  <div className="box-border flex relative flex-col shrink-0 mt-5">
                    <div className="flex gap-5 max-[1040px]:flex-col">
                      <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                        <div className="box-border flex flex-col shrink-0 items-center px-5 pt-5 mt-5 border border-white border-solid max-w-[449px] min-h-[338px] size-full">
                          <div className="flex gap-5 max-[1040px]:flex-col">
                            {/* <div className="border border-red-600 rounded flex flex-col w-[33%] max-[1040px]:ml-0 max-[1040px]:w-full">
                              <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f"
                                className="box-border  object-cover overflow-hidden absolute top-0 left-0 shrink-0 mx-auto mt-5 w-full aspect-[1.25] basis-full grow-0 h-[389px] max-w-[446px] min-h-[20px] min-w-[20px]"
                              />
                            </div> */}
                            {/* <div className="flex flex-col ml-5 w-[33%] max-[1040px]:ml-0 max-[1040px]:w-full">
                              <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F3031152617ff416d87bfe0d49a877dc1?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F3031152617ff416d87bfe0d49a877dc1?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F3031152617ff416d87bfe0d49a877dc1?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F3031152617ff416d87bfe0d49a877dc1?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F3031152617ff416d87bfe0d49a877dc1?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F3031152617ff416d87bfe0d49a877dc1?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F3031152617ff416d87bfe0d49a877dc1?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F3031152617ff416d87bfe0d49a877dc1"
                                className="box-border object-cover overflow-hidden absolute top-0 left-0 shrink-0 mx-auto mt-5 w-full aspect-[1.04] h-[388px] max-w-[446px] min-h-[20px] min-w-[20px] max-[1040px]:hidden"
                              />
                            </div> */}
                            <div className="flex flex-col -mb-16 ml-5 w-[33%] max-[1040px]:ml-0 max-[1040px]:w-full h-[541px]">
                              <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6a35893301314dc49f794d8fe9df397f"
                                className="box-border rounded-md object-cover overflow-hidden absolute top-0 left-0 shrink-0 mx-auto mt-5 w-full aspect-[1.25] h-[541px] max-w-[527px] min-h-[20px] min-w-[20px] max-sm:max-[1040px]:h-[541px] max-sm:h-[388px] max-sm:left-[-41px] max-sm:max-w-[582px] max-sm:w-[337px]"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-[1040px]:ml-0 max-[1040px]:w-full max-[1040px]:-mt-16">
            <div className="flex flex-col px-5 max-[1040px]:mt-24 max-[1040px]:h-auto max-[1040px]:max-h-auto max-[1040px]:min-h-auto max-sm:pb-2 max-sm:my-9 max-sm:min-h-auto">
              <div className="box-border  flex relative flex-col shrink-0 mt-5 mr-auto w-[354px] max-sm:w-[296px]">
                <div className="flex gap-5">
                  <div className="flex flex-col w-12/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto h-auto text-base leading-6 text-amber-500">
                      ––
                    </div>
                  </div>
                  <div className="flex flex-col ml-5 w-6/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-base leading-6 text-amber-500 max-sm:ml-0">
                      WHO WE ARE
                    </div>
                  </div>
                </div>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-4xl leading-10 text-black max-[1040px]:text-4xl">
                <p
                  // class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <b>
                    <span className="text-4xl leading-10">
                      {/* <font face="Poppins, sans-serif" color="#6a7484"> */}
                        <span className="text-4xl leading-10">
                          360 Logistics Operations, powered by tech
                        </span>
                      {/* </font> */}
                    </span>
                  </b>
                </p>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-base text-gray-500 max-sm:bg-white">
                <p
                  class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <span className="text-lg leading-7">
                    <font color="#60697b">
                      Coche Ride platform offers instant access to a diverse
                      range of trucks for your logistics needs across Nigeria
                      and West Africa. Whether you're an individual or an
                      organization, we cater to all your transportation
                      requirements. Our fleet includes minivans and buses to
                      suit various cargo sizes.
                    </font>
                  </span>
                </p>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-base text-gray-500 max-sm:mb-px">
                <p
                  class="p1"
                  className="text-sm normal-nums text-black  leading-[normal] text-start tracking-[normal]"
                >
                  <span className="text-lg leading-7 text-justify text-gray-500 bg-white">
                    We transport all categories of goods, from sensitive items
                    like agricultural produce and pharmaceuticals using our Cold
                    Chain trucks, to general merchandise. Our logistics services
                    are top-notch, with flexible pricing options tailored to
                    your needs.
                  </span>
                  <br />
                </p>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-base text-gray-500">
                <p
                  class="p1"
                  className="text-sm normal-nums text-black  leading-[normal] text-start tracking-[normal]"
                >
                  <span className="text-lg leading-7 text-justify text-gray-500 bg-white">
                    Our tech-enabled digital platform efficiently manages both
                    vehicle owners and drivers, ensuring seamless 360-degree
                    logistics operations throughout Nigeria and West Africa.
                  </span>
                  <br />
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
