/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function FeaturedServiceII() {
  return (
    <div className="box-border flex relative flex-col shrink-0 my-5 bg-white h-[673px] max-[1040px]:px-5 max-[1040px]:mt-0 max-[1040px]:bg-white max-[1040px]:h-[1090px] max-sm:pb-72 max-sm:mt-0 max-sm:bg-white max-sm:h-[30%] max-sm:min-h-[30px] xsm:max-sm:-mt-[900px] ">
      <div className="box-border flex relative flex-col shrink-0 justify-start px-10 pb-20 mt-0 mb-16 bg-white max-sm:px-5 max-sm:mb-5 max-sm:bg-white max-sm:max-h-none max-sm:min-h-[817.5px]">
        <div className="flex gap-5 max-[1040px]:flex-col">
          <div className="flex flex-col w-6/12 max-[1040px]:ml-0 max-[1040px]:w-full">
            <div className="box-border flex relative flex-col shrink-0 px-5 mt-5">
              <div className="flex gap-5 max-[1040px]:flex-col">
                <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                  <div className="box-border flex relative flex-col shrink-0 mt-5">
                    <div className="flex gap-5 max-[1040px]:flex-col">
                      <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                        <div className="box-border flex flex-col shrink-0 items-center px-5 pt-5 mt-5 border border-white border-solid max-w-[449px] min-h-[338px] size-full">
                          <div className="flex gap-5 max-[1040px]:flex-col">
                            <div className="flex flex-col w-[33%] max-[1040px]:ml-0 max-[1040px]:w-full" />
                            <div className="flex flex-col ml-5 w-[33%] max-[1040px]:ml-0 max-[1040px]:w-full" />
                            <div className="flex flex-col ml-5 w-[33%] max-[1040px]:ml-0 max-[1040px]:w-full">
                              <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe9b61521c4524c508ef00fd37baa47f3?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe9b61521c4524c508ef00fd37baa47f3?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe9b61521c4524c508ef00fd37baa47f3?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe9b61521c4524c508ef00fd37baa47f3?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe9b61521c4524c508ef00fd37baa47f3?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe9b61521c4524c508ef00fd37baa47f3?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe9b61521c4524c508ef00fd37baa47f3?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe9b61521c4524c508ef00fd37baa47f3"
                                className="box-border object-cover overflow-hidden absolute left-0 shrink-0 mx-auto mt-5 w-full aspect-[1.51] h-[420px] max-w-[679px] min-h-[20px] min-w-[20px] top-[18px] max-sm:h-[388px] max-sm:max-w-[582px] max-sm:min-w-[300px] xsm:max-sm:-ml-4"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-[1040px]:ml-0 max-[1040px]:w-full">
            <div className="flex flex-col px-5 max-[1040px]:mt-20 max-[1040px]:h-[600px] max-[1040px]:max-h-[600px] max-[1040px]:min-h-[600px] max-sm:pb-2 max-sm:my-9 max-sm:min-h-[600p]">
              <div className="box-border flex relative flex-col shrink-0 mt-5 mr-auto w-[354px] max-sm:w-[296px]">
                <div className="flex gap-5">
                  <div className="flex flex-col w-12/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto h-auto text-base leading-6 text-amber-500">
                      ––
                    </div>
                  </div>
                  <div className="flex flex-col ml-5 w-12/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-base leading-6 text-amber-500 max-sm:ml-0">
                      {/* <font face="Poppins, sans-serif"> */}
                        FEATURED SERVICE
                      {/* </font> */}
                    </div>
                  </div>
                </div>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-4xl leading-10 text-black max-[1040px]:text-4xl">
                <p
                  // class="p1"
                  className="text-sm normal-nums leading-[normal] text-start tracking-[normal]"
                >
                  <b>
                    <span className="text-4xl leading-10">
                      {/* <font face="Poppins, sans-serif" color="#6a7484"> */}
                        <span className="text-4xl leading-10 text-[#6a7484]">
                          Coche Ride Coaster Buses and Minivans: Versatile
                          Transportation Solutions
                        </span>
                      {/* </font> */}
                    </span>
                  </b>
                </p>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-base text-gray-500 max-sm:bg-white">
                <p
                  // class="p1"
                  className="text-sm normal-nums leading-[normal] text-start tracking-[normal]"
                >
                  <span className="text-base leading-7 text-justify text-gray-500 bg-white">
                    Coche Ride offers a comprehensive fleet of coaster buses and
                    minivans, perfect for all your transportation needs. Whether
                    you're moving small groups, organizing events, or
                    transporting goods, our vehicles provide a reliable and
                    efficient solution.
                  </span>
                  <br />
                </p>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto">
                <span className="text-base leading-7 text-justify text-gray-500 bg-white">
                  {/* <font face="Poppins, sans-serif"> */}
                    Our coaster buses and minivans are equipped with modern
                    amenities and safety features to ensure a comfortable and
                    secure journey. With GPS tracking and real-time updates, you
                    can monitor your trips and ensure timely arrivals. Flexible
                    booking options and competitive pricing make Coche Ride the
                    go-to choice for versatile transportation.
                  {/* </font> */}
                </span>
                <br />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
