/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function Partners() {
  return (
    <div className="box-border flex relative flex-col shrink-0 mx-auto mt-48 mb-5 bg-white h-[673px] max-md:px-5 max-md:mt-0 max-md:bg-white max-md:h-[1090px] max-sm:mt-0 max-sm:h-auto max-sm:bg-white max-sm:min-h-[auto]">
      <div className="box-border flex relative flex-col shrink-0 justify-start px-10 pb-20 mx-auto mt-0 mb-16 bg-white max-sm:px-5 max-sm:pb-40 max-sm:mb-5 max-sm:bg-white max-sm:max-h-none max-sm:min-h-[817.5px]">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col px-5 max-md:mt-20 max-md:h-[600px] max-md:max-h-[600px] max-md:min-h-[600px] max-sm:pb-2 max-sm:my-9 max-sm:min-h-[600p]">
              <div className="box-border flex relative flex-col shrink-0 mt-5 mr-auto w-[354px] max-sm:w-[296px]">
                <div className="flex gap-5">
                  <div className="flex flex-col w-6/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto h-auto text-base leading-6 text-amber-500">
                      ––
                    </div>
                  </div>
                  <div className="flex flex-col ml-5 w-6/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-base leading-6 text-amber-500 max-sm:ml-0">
                      {/* <font face="Poppins, sans-serif"> */}
                        PARTNERS &amp; CLIENTS
                      {/* </font> */}
                    </div>
                  </div>
                </div>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-4xl leading-10 text-black max-md:text-4xl">
                <p
                  // class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <b>
                    <span className="text-4xl leading-10">
                      {/* <font face="Poppins, sans-serif" color="#6a7484"> */}
                        <span className="text-4xl leading-10 text-[#6a7484]">
                          Trusted by Over 20+ Partners &amp; Clients
                        </span>
                      {/* </font> */}
                    </span>
                  </b>
                </p>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-base text-gray-500 max-sm:bg-white">
                <p
                  // class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <span className="text-xl font-medium leading-9 text-justify bg-white">
                    {/* <font color="#60697b"> */}
                      <span className="">
                        Our Partners and Clients form the backbone of success.
                        With a proven track record of excellence, we collaborate
                        seamlessly to deliver efficient and reliable logistics
                        solution.
                      </span>
                    {/* </font> */}
                  </span>
                  <span className="text-xl font-medium leading-9 text-justify text-gray-500 bg-white">
                    &nbsp;
                  </span>
                  <br />
                </p>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto">
                <span className="text-base leading-7 text-justify text-gray-500 bg-white">
                  {/* <font face="Poppins, sans-serif"> */}
                    <span className="text-xl leading-9 ">
                      From multinational corporations to local enterprises, our
                      dedication to personalized service, cutting edge
                      technology, and unwavering commitment to meeting unique
                      logistical needs sets us apart.&nbsp;
                    </span>
                  {/* </font> */}
                </span>
                <br />
              </div>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[67%] max-md:ml-0 max-md:w-full">
            <div className="box-border flex relative flex-col shrink-0 px-5 mt-5 max-md:mt-0 max-sm:pr-8 max-sm:mt-44">
              <div className="flex gap-5">
                <div className="flex flex-col w-full">
                  <div className="box-border grid relative flex-row shrink-0 mt-5 grid-cols-[repeat(1,1fr)] max-sm:grid max-sm:flex-row max-sm:mt-5 max-sm:grid-cols-[repeat(1,1fr)]">
                    <div className="box-border grid flex-col shrink-0 items-center px-5 pt-5 mt-5 grid-cols-[repeat(;media-max-width-640-px:[object_Object];border:1px_solid_rgba(255,255,255,1);}] size-full max-sm:mt-20 max-sm:mr-auto">
                      <div className="flex gap-5 max-sm:flex-col">
                        <div className="flex flex-col w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F07408b6f1af64734bbcb3548cdde4227?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F07408b6f1af64734bbcb3548cdde4227?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F07408b6f1af64734bbcb3548cdde4227?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F07408b6f1af64734bbcb3548cdde4227?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F07408b6f1af64734bbcb3548cdde4227?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F07408b6f1af64734bbcb3548cdde4227?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F07408b6f1af64734bbcb3548cdde4227?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F07408b6f1af64734bbcb3548cdde4227"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F0c1f38c6708540a2b1b0a5f55598afb5?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F0c1f38c6708540a2b1b0a5f55598afb5?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F0c1f38c6708540a2b1b0a5f55598afb5?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F0c1f38c6708540a2b1b0a5f55598afb5?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F0c1f38c6708540a2b1b0a5f55598afb5?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F0c1f38c6708540a2b1b0a5f55598afb5?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F0c1f38c6708540a2b1b0a5f55598afb5?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F0c1f38c6708540a2b1b0a5f55598afb5"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6ce14c20ba5d42ac854e90ee19af47c6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6ce14c20ba5d42ac854e90ee19af47c6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6ce14c20ba5d42ac854e90ee19af47c6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6ce14c20ba5d42ac854e90ee19af47c6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6ce14c20ba5d42ac854e90ee19af47c6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6ce14c20ba5d42ac854e90ee19af47c6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6ce14c20ba5d42ac854e90ee19af47c6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F6ce14c20ba5d42ac854e90ee19af47c6"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F89edde25113446c6a8f00171363485c0?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F89edde25113446c6a8f00171363485c0?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F89edde25113446c6a8f00171363485c0?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F89edde25113446c6a8f00171363485c0?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F89edde25113446c6a8f00171363485c0?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F89edde25113446c6a8f00171363485c0?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F89edde25113446c6a8f00171363485c0?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F89edde25113446c6a8f00171363485c0"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                      </div>
                    </div>
                    <div className="box-border grid flex-col shrink-0 items-center px-5 pt-5 mt-5 grid-cols-[repeat(;media-max-width-640-px:[object_Object];border:1px_solid_rgba(255,255,255,1);}] size-full max-sm:mt-0">
                      <div className="flex gap-5 max-sm:flex-col">
                        <div className="flex flex-col w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F043296c222df45d19bc48c7c2f2ff0c4?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F043296c222df45d19bc48c7c2f2ff0c4?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F043296c222df45d19bc48c7c2f2ff0c4?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F043296c222df45d19bc48c7c2f2ff0c4?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F043296c222df45d19bc48c7c2f2ff0c4?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F043296c222df45d19bc48c7c2f2ff0c4?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F043296c222df45d19bc48c7c2f2ff0c4?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F043296c222df45d19bc48c7c2f2ff0c4"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F48a8cec1f2eb44108726b32b1b0d6147?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F48a8cec1f2eb44108726b32b1b0d6147?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F48a8cec1f2eb44108726b32b1b0d6147?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F48a8cec1f2eb44108726b32b1b0d6147?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F48a8cec1f2eb44108726b32b1b0d6147?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F48a8cec1f2eb44108726b32b1b0d6147?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F48a8cec1f2eb44108726b32b1b0d6147?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F48a8cec1f2eb44108726b32b1b0d6147"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5b7bc5d0a0234a3899a7ccde1d030e31?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5b7bc5d0a0234a3899a7ccde1d030e31?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5b7bc5d0a0234a3899a7ccde1d030e31?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5b7bc5d0a0234a3899a7ccde1d030e31?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5b7bc5d0a0234a3899a7ccde1d030e31?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5b7bc5d0a0234a3899a7ccde1d030e31?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5b7bc5d0a0234a3899a7ccde1d030e31?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5b7bc5d0a0234a3899a7ccde1d030e31"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5e0037a761e04f8dbb8f0ca57b10f9cf?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5e0037a761e04f8dbb8f0ca57b10f9cf?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5e0037a761e04f8dbb8f0ca57b10f9cf?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5e0037a761e04f8dbb8f0ca57b10f9cf?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5e0037a761e04f8dbb8f0ca57b10f9cf?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5e0037a761e04f8dbb8f0ca57b10f9cf?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5e0037a761e04f8dbb8f0ca57b10f9cf?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5e0037a761e04f8dbb8f0ca57b10f9cf"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                      </div>
                    </div>
                    <div className="box-border grid flex-col shrink-0 items-center px-5 pt-5 mt-5 grid-cols-[repeat(;border:1px_solid_rgba(255,255,255,1);}] size-full">
                      <div className="flex gap-5 max-sm:flex-col">
                        <div className="flex flex-col w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2b67b62d2a840938b1939c59b8c4908?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2b67b62d2a840938b1939c59b8c4908?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2b67b62d2a840938b1939c59b8c4908?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2b67b62d2a840938b1939c59b8c4908?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2b67b62d2a840938b1939c59b8c4908?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2b67b62d2a840938b1939c59b8c4908?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2b67b62d2a840938b1939c59b8c4908?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2b67b62d2a840938b1939c59b8c4908"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fdf11041da23845ce901349c430446511?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fdf11041da23845ce901349c430446511?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fdf11041da23845ce901349c430446511?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fdf11041da23845ce901349c430446511?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fdf11041da23845ce901349c430446511?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fdf11041da23845ce901349c430446511?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fdf11041da23845ce901349c430446511?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fdf11041da23845ce901349c430446511"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7a9be184b7444391b390c188e85a5a5f?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7a9be184b7444391b390c188e85a5a5f?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7a9be184b7444391b390c188e85a5a5f?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7a9be184b7444391b390c188e85a5a5f?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7a9be184b7444391b390c188e85a5a5f?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7a9be184b7444391b390c188e85a5a5f?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7a9be184b7444391b390c188e85a5a5f?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7a9be184b7444391b390c188e85a5a5f"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff056b6ead84b4d5f8681b349040d0c92?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff056b6ead84b4d5f8681b349040d0c92?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff056b6ead84b4d5f8681b349040d0c92?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff056b6ead84b4d5f8681b349040d0c92?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff056b6ead84b4d5f8681b349040d0c92?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff056b6ead84b4d5f8681b349040d0c92?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff056b6ead84b4d5f8681b349040d0c92?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ff056b6ead84b4d5f8681b349040d0c92"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                      </div>
                    </div>
                    <div className="box-border grid flex-col shrink-0 items-center px-5 pt-5 mt-5 grid-cols-[repeat(;border:1px_solid_rgba(255,255,255,1);}] size-full">
                      <div className="flex gap-5 max-sm:flex-col">
                        <div className="flex flex-col w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F4ac6edd6c2784314ab8d4cb3a66d7bf9?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F4ac6edd6c2784314ab8d4cb3a66d7bf9?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F4ac6edd6c2784314ab8d4cb3a66d7bf9?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F4ac6edd6c2784314ab8d4cb3a66d7bf9?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F4ac6edd6c2784314ab8d4cb3a66d7bf9?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F4ac6edd6c2784314ab8d4cb3a66d7bf9?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F4ac6edd6c2784314ab8d4cb3a66d7bf9?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F4ac6edd6c2784314ab8d4cb3a66d7bf9"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9c860ba6aa0d49e389e5c78d9e813981?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9c860ba6aa0d49e389e5c78d9e813981?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9c860ba6aa0d49e389e5c78d9e813981?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9c860ba6aa0d49e389e5c78d9e813981?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9c860ba6aa0d49e389e5c78d9e813981?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9c860ba6aa0d49e389e5c78d9e813981?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9c860ba6aa0d49e389e5c78d9e813981?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9c860ba6aa0d49e389e5c78d9e813981"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Facebad2455c549ee8afb737c09dae613?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Facebad2455c549ee8afb737c09dae613?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Facebad2455c549ee8afb737c09dae613?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Facebad2455c549ee8afb737c09dae613?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Facebad2455c549ee8afb737c09dae613?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Facebad2455c549ee8afb737c09dae613?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Facebad2455c549ee8afb737c09dae613?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Facebad2455c549ee8afb737c09dae613"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                        <div className="flex flex-col ml-5 w-3/12 max-sm:ml-0 max-sm:w-full">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F44b3304a895a4021ab1e0258bd351acc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F44b3304a895a4021ab1e0258bd351acc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F44b3304a895a4021ab1e0258bd351acc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F44b3304a895a4021ab1e0258bd351acc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F44b3304a895a4021ab1e0258bd351acc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F44b3304a895a4021ab1e0258bd351acc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F44b3304a895a4021ab1e0258bd351acc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F44b3304a895a4021ab1e0258bd351acc"
                            className="box-border object-cover overflow-hidden shrink-0 ml-5 w-full aspect-[1.49] min-h-[20px] min-w-[20px]"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
