/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function WhyChooseUs() {
  return (
    <div className="box-border flex relative flex-col shrink-0 pb-32 mt-24 mb-20 h-auto bg-neutral-100 max-[1040px]:mt-0 max-sm:mt-1">
      <div className="box-border flex relative flex-col shrink-0 px-10 mt-7 max-[1040px]:mt-5 max-sm:mt-10">
        <div className="flex gap-5 max-[1040px]:flex-col">
          <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
            <div className="px-5 mt-7">
              <div className="box-border flex relative flex-col shrink-0 mt-5 w-[347px]">
                <div className="flex gap-5">
                  <div className="flex flex-col w-12/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto h-auto text-base leading-6 text-amber-500">
                      ––
                    </div>
                  </div>
                  <div className="flex flex-col ml-5 w-6/12">
                    <div className="box-border relative shrink-0 mt-5 mr-auto ml-0 h-auto text-base leading-6 text-amber-500">
                      WHY CHOOSE US
                    </div>
                  </div>
                </div>
              </div>
              <div className="box-border relative shrink-0 mt-5 h-auto text-4xl leading-10 text-black">
                <p
                  // class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <b>
                    <span className="text-4xl leading-10">
                      {/* <font face="Poppins, sans-serif" color="#6a7484"> */}
                        <span className="text-4xl leading-10">
                          We make logistics easy for everyone. With just a few
                          clicks on your phone, you can book a truck or a bus
                          for your freight needs.
                        </span>
                      {/* </font> */}
                    </span>
                  </b>
                </p>
              </div>
              <div className="main_container box-border grid relative gap-5 mt-5 grid-cols-[repeat(4,1fr)] max-[1040px]:grid-cols-[repeat(2,1fr)] max-sm:grid max-sm:flex-row max-sm:grid-cols-[repeat(1,1fr)]">
                <div className="column box-border flex relative flex-col shrink-0 mt-5">
                  <div className="flex gap-5">
                    <div className="flex flex-col w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F9be841b2a8184e928fe808fdadf49a3e"
                        className="box-border object-cover overflow-hidden shrink-0 mt-5 mr-auto w-full aspect-square max-w-[46px] min-h-[20px] min-w-[20px]"
                      />
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <h4 className="mb-2 text-base font-bold tracking-normal leading-normal">
                          <span className="text-xl bg-white">
                            {/* <font color="#343f53" face="Poppins, sans-serif"> */}
                              Flexible Pricing + Timely Delivery
                            {/* </font> */}
                          </span>
                        </h4>
                      </div>
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <span className="text-justify text-gray-500 bg-neutral-100">
                          {/* <font face="Poppins, sans-serif"> */}
                            Our pricing, primarily determined by distance, is
                            flexible and more affordable than industry
                            standards. Thanks to our advanced road technology,
                            our trucks consistently arrive faster than
                            estimated.
                          {/* </font> */}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="column box-border flex relative flex-col shrink-0 mt-5">
                  <div className="flex gap-5 max-[1040px]:flex-col">
                    <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F7cb29e54a877479b9f965dc9807a8d93"
                        className="box-border object-cover overflow-hidden shrink-0 mt-5 mr-auto w-full aspect-square max-w-[46px] min-h-[20px] min-w-[20px]"
                      />
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <h4 className="mb-2 font-bold tracking-normal leading-normal bg-neutral-100 text-slate-700">
                          <span className="text-xl">
                            Instant and Unrivaled Access to Fleet of Trucks
                          </span>
                        </h4>
                      </div>
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <span className="text-lg leading-7 text-justify text-gray-500 bg-neutral-100">
                          {/* <font face="Poppins, sans-serif"> */}
                            With a network of over 20,000 trucks, buses, and
                            minivans across Nigeria and West Africa, we
                            guarantee access to a vehicle within 2 minutes of
                            your request.
                          {/* </font> */}
                        </span>
                        <br />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="column box-border flex relative flex-col shrink-0 mt-5">
                  <div className="flex gap-5 max-[1040px]:flex-col">
                    <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc29b2390e1f4499090ea7c2fcbcd63f0"
                        className="box-border object-cover overflow-hidden shrink-0 p-2.5 mt-5 mr-auto w-full text-amber-500 bg-white accent-amber-500 aspect-square fill-amber-500 max-w-[46px] min-h-[20px] min-w-[20px]"
                      />
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <h4 className="mb-2 text-base font-bold tracking-normal leading-normal bg-neutral-100 text-slate-700">
                          <span className="text-xl">
                            {/* <font face="Poppins, sans-serif"> */}
                              Real-Time Tracking + Auto Insurance Coverage
                            {/* </font> */}
                          </span>
                        </h4>
                      </div>
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <span className="text-lg leading-7 text-justify text-gray-500 bg-neutral-100">
                          {/* <font face="Poppins, sans-serif"> */}
                            Enjoy 360-degree visibility and real-time updates on
                            your goods in transit, along with automated
                            insurance coverage of your goods.
                          {/* </font> */}
                        </span>
                        <br />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="column box-border flex relative flex-col shrink-0 mt-5">
                  <div className="flex gap-5 max-[1040px]:flex-col">
                    <div className="flex flex-col w-full max-[1040px]:ml-0 max-[1040px]:w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fb464a008fea646a4ae4505b3f196ef11"
                        className="box-border object-cover overflow-hidden shrink-0 mt-5 mr-auto w-full text-amber-500 bg-white accent-amber-500 aspect-square fill-amber-500 max-w-[46px] min-h-[20px] min-w-[20px]"
                      />
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <h4 className="mb-2 text-base font-bold tracking-normal leading-normal bg-neutral-100 text-slate-700">
                          <span className="text-xl">
                            {/* <font face="Poppins, sans-serif"> */}
                              Technology + 24/7 Customer Support
                            {/* </font> */}
                          </span>
                        </h4>
                      </div>
                      <div className="box-border relative shrink-0 mt-5 h-auto">
                        <span className="text-lg text-justify text-gray-500 bg-neutral-100">
                          {/* <font face="Poppins, sans-serif"> */}
                            <span className="leading-7">
                              Our tech-driven platform connects you with a
                              network of registered and verified vehicles,
                              supported by a 24/7 customer support team ready to
                              resolve any issues.
                            </span>
                          {/* </font> */}
                        </span>
                        <br />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
