/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function Testimonials() {
  return (
    <div className="box-border flex relative flex-col shrink-0 pt-32 mt-0 mb-5 bg-white h-[673px] max-md:px-5 max-md:mt-0 max-md:bg-white max-md:h-[1090px] max-sm:pb-72 max-sm:bg-white max-sm:h-[30%] max-sm:min-h-[30px]">
      <div className="box-border flex relative flex-col shrink-0 justify-start px-10 pb-20 mx-auto mt-0 mb-16 bg-white max-sm:px-5 max-sm:mb-5 max-sm:bg-white max-sm:max-h-none max-sm:min-h-[817.5px]">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="box-border flex relative flex-col shrink-0 px-5 mt-5">
              <div className="flex gap-5 max-md:flex-col">
                <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                  <div className="box-border flex relative flex-col shrink-0 mt-5">
                    <div className="flex gap-5 max-md:flex-col">
                      <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                        <div className="box-border flex flex-col shrink-0 items-center px-5 pt-5 mt-5 border border-white border-solid max-w-[449px] min-h-[338px] size-full">
                          <div className="flex gap-5 max-md:flex-col">
                            <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full" />
                            <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full" />
                            <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                              <img
                                loading="lazy"
                                srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F369ac11ae27748e5b9c3edebac3820ad?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F369ac11ae27748e5b9c3edebac3820ad?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F369ac11ae27748e5b9c3edebac3820ad?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F369ac11ae27748e5b9c3edebac3820ad?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F369ac11ae27748e5b9c3edebac3820ad?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F369ac11ae27748e5b9c3edebac3820ad?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F369ac11ae27748e5b9c3edebac3820ad?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F369ac11ae27748e5b9c3edebac3820ad"
                                className="box-border object-cover overflow-hidden absolute left-0 shrink-0 mx-auto mt-5 w-full aspect-[1.37] h-[420px] max-w-[679px] min-h-[20px] min-w-[20px] top-[18px] max-sm:h-[388px] max-sm:left-[-41px] max-sm:max-w-[582px] max-sm:w-[337px]"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col px-5 mt-auto max-md:mt-20 max-md:h-[600px] max-md:max-h-[600px] max-md:min-h-[600px] max-sm:pb-2 max-sm:my-9 max-sm:min-h-[600p]">
              <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-4xl leading-10 text-black max-md:text-4xl">
                <p
                  class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <b>
                    <span className="text-4xl leading-10">
                      <font face="Poppins, sans-serif" color="#6a7484">
                        <span className="text-4xl leading-10">“‘””</span>
                      </font>
                    </span>
                  </b>
                </p>
              </div>
              <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-base text-gray-500 max-sm:bg-white">
                <p
                  class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <span className="text-base leading-7 text-justify text-gray-500 bg-white">
                    &quot;Your team's effort have been impeccable from the start
                    and you never let us down. If I could recommend any service
                    provider to a fowarding agent, it will be Coche.&quot;
                  </span>
                  <br />
                </p>
              </div>
              <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-base text-gray-500 max-md:mx-auto max-sm:bg-white">
                <p
                  class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <span className="self-center text-base font-bold leading-7 text-justify text-gray-500 bg-white">
                    Olabode Ajayi
                  </span>
                  <br />
                </p>
              </div>
              <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-base text-gray-500 max-md:mx-auto max-sm:bg-white">
                <p
                  class="p1"
                  className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                >
                  <span className="self-center text-base font-medium leading-7 text-justify text-gray-500 bg-white">
                    Logistics Manager | Tolz
                  </span>
                  <br />
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
