import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import { Nunito } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Template from "./template";
// import MainHeader from "./components/MainHeader";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight:"400"})
const nunito = Nunito({subsets: ['latin-ext'], weight:'400'})
const monteserrat = Montserrat({subsets: ["latin-ext"], weight:'400'})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} w-screen`}>
        <Template>
        {children}
        </Template>
      </body>
    </html>
  );
}
